firstProject/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/',
         auth_views.LoginView.as_view(template_name='accounts/login.html'),
         name='login'
     ),
     path('logout/',
         auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
         name='logout'
     ),
]

firstProject/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [ 
    path('', views.IndexView.as_view(), name='index'),
    path('post/', views.PostArticleView.as_view(), name='post_article'),
    path('detail/<int:id>/', views.DetailArticleView.as_view(), name='detail_article'),
    path('edit/<int:id>/', views.edit_article, name='edit_article'),
    path('mypage/', views.MyPageView.as_view(), name='mypage'),
]

firstProject/firstProject/urls.py
from django.contrib import admin
from django.urls import path,include
from blog.views import IndexView
from django.conf import settings									
from django.conf.urls.static import static							



urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstProject/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    kana = models.CharField(				
        verbose_name='氏名カナ',				
        max_length=40,			
        null = True,						
        blank=True,							
    )

firstProject/blog/models.py
from django.db import models
from accounts.models import CustomUser

class Category(models.Model):
    title = models.CharField(
        verbose_name='カテゴリ',
        max_length=20
    )

    def __str__(self):
        return self.title

class BlogPost(models.Model):
    user = models.ForeignKey(
        to=CustomUser,
        verbose_name='ユーザ',
        on_delete=models.CASCADE,
        null=True
    )

    category = models.ForeignKey(
        to=Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT,
        null=True
    )

    title = models.CharField(
        verbose_name='タイトル',
        max_length=20
    )

    content = models.TextField(
        verbose_name='本文'
    )

    posted_id = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )

    image = models.ImageField(				
        verbose_name='イメージ',				
        upload_to ='photos',				
        null = True,						
        blank=True,							
    )

    def __str__(self):
        return self.title

firstProject/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CreateCustomUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["username","kana","email","password1","password2"]
        labels = {
            "username":"ユーザー名",
            "kana": "氏名カナ",
            "email":"メールアドレス",
            "password1":"パスワード",
            "password2":"パスワード（確認用）",
        }

firstProject/blog/forms.py
from django import forms
from .models import BlogPost

class SearchForm(forms.Form):
    key = forms.CharField(label='検索文字列')

class PostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ["title","content","category","image"]
        labels = {
            "title":"題名",
            "content":"本文",
            "category":"カテゴリ",
            "image":"画像",
        }

firstProject/accounts/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,FormView,CreateView
from django.urls import reverse_lazy
from .forms import CreateCustomUserForm
from .models import CustomUser

class SignUpView(CreateView):
    model = CustomUser											
    template_name ='accounts/signup.html'
    form_class = CreateCustomUserForm
    success_url = reverse_lazy('accounts:signup_success')

class SignUpSuccessView(TemplateView):
    template_name = 'accounts/signup_success.html'

firstProject/blog/views.py
from datetime import datetime
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView,DetailView,FormView,CreateView
from blog.models import BlogPost
from .forms import SearchForm,PostForm
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator		
from django.contrib.auth.decorators import login_required

class IndexView(ListView):
    template_name = 'blog/index.html'
    # queryset = BlogPost.objects.order_by('-posted_id')
    context_object_name = 'orderby_records'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context

    def get_queryset(self):
        searchForm = SearchForm(self.request.GET)
        keyword = ''
        if searchForm.is_valid():
            keyword = searchForm.cleaned_data.get('key')
        queryset = BlogPost.objects.filter(title__contains=keyword).order_by('-posted_id')
        return queryset

@method_decorator(login_required, name='dispatch')
class PostArticleView(CreateView):
    model = BlogPost
    template_name = 'blog/create_post.html'
    form_class = PostForm
    success_url = reverse_lazy("blog:index")

    def form_valid(self, form):
         # commit=FalseにしてPOSTされたデータを取得
         postdata = form.save(commit=False)
         # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
         postdata.user = self.request.user
         # 投稿データをデータベースに登録
         postdata.save()
         # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
         return super().form_valid(form)

class DetailArticleView(DetailView):
    template_name = 'blog/detail_article.html'
    model = BlogPost
    pk_url_kwarg = 'id'


def edit_article(request, id):
    return HttpResponse(f'記事:{id}番目を編集します。')

class MyPageView(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'orderby_records'
    paginate_by = 4
    def get_queryset(self):
        queryset = BlogPost.objects.filter(user=self.request.user)
        return queryset
    

firstProject/templates/accounts/login.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更 -->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <!-- タイトル変更 -->
    <title>Log in</title>
    
    <!-- <link rel="canonical"...>を削除 -->

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
    <!-- 「static/css/signin.css」の読み込み -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>
  
  <body class="text-center">
    <main class="form-signin">
      <!-- ユーザー名とパスワードが一致しない場合のメッセージ -->
      {% if form.errors %}
        <p style="color: red">ユーザー名とパスワードが一致しません。</p>
      {% endif %}

      <!-- ログインのフォームを配置 -->
      <form method="post">
        {% csrf_token %}  
        <!-- Bootstrapのロゴを表示 -->
        <!-- 「static/img/bootstrap-logo.svg」の読み込み -->
        <img class="mb-4"
             src="{% static 'img/bootstrap-logo.svg' %}"
             alt="" width="72"
             height="57">
        <h1 class="h3 mb-3 fw-normal">Please Log in</h1>
        <!-- Usernameのラベル(非表示) -->
        <label for="Username" class="visually-hidden">
          User name</label>
        <!-- usernameの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名username -->
        <input type="text"
               name="username"
               id="id_username"
               maxlength="150"
               autocapitalize="none"
               autocomplete="username"
               class="form-control"
               placeholder="ユーザー名"
               required autofocus>
        <!-- Passwordのラベル(非表示) -->
        <label for="Password" class="visually-hidden">
          Password</label>
        <!-- passwordの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名password -->
        <input type="password"
               name="password"
               id="id_password"
               autocomplete="current-password"
               class="form-control"
               placeholder="パスワード"
               required>
        <!-- <div class="checkbox mb-3">～</div>削除 -->
        <!-- <button>～</button>を書き換えてログインボタンを配置 -->
        <input class="w-100 btn btn-lg btn-primary"
               type="submit" value="ログイン">
        <!-- ログイン直後のリダイレクト先(トップページ)のURLパターンを設定 -->
        <input type="hidden"
               name="next"
               value="{% url 'blog:index' %}">
      </form>
    </main>
  </body>
</html>

firstProject/templates/accounts/logout.html
<!-- ベーステンプレートを適用する -->
{% extends 'blog/base.html' %}
{% load static %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Log out{% endblock %}
{% block header %}
<header class="masthead"
          style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="site-heading">
            <!-- ヘッダーの大見出し(タイトル)を変更 -->
            <h1>Signout</h1>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}
{% block contents %}
<!-- Bootstrapのグリッドシステム -->
<div class="container">
  <!-- 行を配置 -->
  <div class="row">
    <!-- 列の左右に余白offset-4を入れる
          列の上下パディングはpy-4 -->
    <div class="col offset-4 py-4">

    <h3>ログアウトしました</h3>
    <!-- トップページのリンクテキスト -->
    <p><a href="{% url 'blog:index' %}">トップページへ</a><p>
{% endblock %}

firstProject/templates/accounts/signup.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title%}Signup{% endblock %}

{% block header%}

<header class="masthead" style="background-image: url({% static 'img/about-bg.jpg'%})">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Signup</h1>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}
{% block contents%}
<div class="container">
  <!-- 行を配置 -->
  <div class="row">
    <!-- 列の左右に余白offset-2を入れる -->
    <div class="col offset-2">
      <h3>サインアップ</h3>
      <!-- サインアップのフォームを配置 -->
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
          {{ field.label_tag }}<br>
          {{ field }}
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
        <p style="color:red">{{ error }}</p>
        {% endfor %}
        </p>
        {% endfor %}
        <input type="submit" value="サインアップ">
      </form>
      <br>
      <p><a href="{ url 'blog:index' }">
          登録をやめてトップページに戻る</a>
      </p>
    </div>
  </div>
</div>
{% endblock %}

firstProject/templates/accounts/signup_success.html
<!-- ベーステンプレートを適用する -->
{% extends 'blog/base.html' %}
{% load static %} 
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Registration Complete{% endblock %}
{% block header %}
<header class="masthead"
          style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="site-heading">
            <!-- ヘッダーの大見出し(タイトル)を変更 -->
            <h1>Signup</h1>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block contents %}
<!-- Bootstrapのグリッドシステム -->
<div class="container">
  <!-- 行を配置 -->
  <div class="row">
    <!-- 列の左右に余白offset-4を入れる
          列の上下パディングはpy-4 -->
    <div class="col offset-4 py-4">
      <h3>登録が完了しました</h3>
      <!-- ログインページのリンクテキスト -->
      <p><a href="#">ログインはこちら</a><p>
    </dv>
  </dv>
</dv>
{% endblock %}

firstProject/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>{% block title%}{% endblock%}</title>
  <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
  <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
    type="text/css" />
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
    rel="stylesheet" type="text/css" />
  <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="{% url 'blog:index' %}">Django's Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto py-4 py-lg-0">
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:index'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:post_article'%}">POST</a>
          </li>
          {% if user.is_authenticated %}
          <!-- <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:logout' %}">LOGOUT</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="javascript:logout.submit()">LOGOUT</a>
          </li>
          <form action='{% url "accounts:logout" %}' method='post' name='logout' style="display: none;">
            {% csrf_token %}
          </form>
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:mypage' %}">{{ user.username }}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:login' %}">LOGIN</a>
          </li>
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:signup' %}">SIGNUP</a>
          </li>
          {% endif %}
        </ul>
        <form method="GET" action="/" class="w-50 h-25">
          <div class="input-group">
            <!-- <input type="text" id="key" name="key"> -->
            {{ search_form.key }}
            <button class="btn btn-primary py-1 yx-5" id="button-search" type="submit">Go!</button>
          </div>
        </form>
      </div>
    </div>
  </nav>
  {% block header%}{% endblock %}
  {% block contents%}{% endblock %}
  <footer>
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://twitter.com/">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.facebook.com/">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://github.co.jp/">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <div class="small text-center text-muted fst-italic">
            Copyright &copy; Djang's Blog 2021</div>
        </div>
      </div>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{% static 'js/scripts.js'%}"></script>
</body>

</html>

firstProject/templates/blog/create_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title%}Django's Blog - 投稿{% endblock %}

{% block header%}
<header class="masthead" style="background-image: url(/static/img/post-sample-image.jpg)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Post New Article</h1>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block contents%}
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <div class="my-5">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-floating">
            <div class="form-group floating-label-form-group controls">
              {{ field.label_tag }}
              {{ field }}
              {% for err in field.errors %}
              <p class="help-block text-danger">{{ err }}</p>
              {% endfor %}
            </div>
          </div>
          {% endfor %}
          <br>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Post</button>
        </form>
      </div>
    </div>
  </div>
</div>
<hr>
{% endblock %}

firstProject/templates/blog/detail_article.html
{% extends 'blog/base.html' %}
{% load static %}


{% block title%}Django's Blog - 詳細ページ{% endblock %}

{% block header%}
<header class="masthead" style="background-image: url(/static/img/post-bg.jpg)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-heading">
          <h1>{{ object.title }}</h1>
          <h2 class="subheading">{{ object.content | truncatechars:30}}</h2>
          <span class="meta">
            <a href="index.html">Django's Blog</a>
            {{ object.posted_id | date:"y/m/d"}} {{ object.posted_id | time:"H:i"}}に投稿に投稿／カテゴリ:
            {{object.category.title}}</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block contents%}
{% include 'blog/sidebar.html' %}
<article class="col-sm-9 mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5">
      <p>{{ object.content }}</p>
      {% if object.image %}
      <img src="{{ object.image.url }}" class="bd-placeholder-img card-img-top w-50">
      {% endif %}
    </div>
  </div>
</article>
</div>
<hr>
{% endblock %}

firstProject/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title%}Django's Blog{% endblock %}

{% block header%}
<header class="masthead" style="background-image: url({% static 'img/home-bg.jpg'%})">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <!-- ヘッダーの大見出し(タイトル)を変更 -->
          <h1>Django's Blog</h1>
          <!-- サブタイトルを変更 -->
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block contents%}
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      {% for record in orderby_records %}
      <div class="post-preview">
        <a href="{% url 'blog:detail_article' record.pk %}">
          <h2 class="post-title">
            {{ record.title }}
          </h2>
          <h3 class="post-subtitle">
            <span style="font-size : 16pt">
              {{ record.content | truncatechars:15}}
            </span>
          </h3>
        </a>
        <p class="post-meta">
          <a href="#">Django's Blog</a>
          2022年1月27日16:12に投稿／カテゴリ:{{ record.category.title }}
        </p>
      </div>
      <hr class="my-4" />
      {% endfor %}
      {% if is_paginated %}
      {% include 'blog/pagenation.html' %}
      {% endif %}
    </div>
  </div>
</div>
<hr class="my-4" />
{% endblock %}

firstProject/templates/blog/pagenation.html
<ul class="pagination" style="justify-content:center">
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
      <span aria-hidden="true">&laquo;</span>
    </a>
  </li>
  {% endif %}
  {% for num in paginator.page_range %}
  {% if page_obj.number == num %}
  <li class="page-item active">
    <span class="page-link">{{ num }}</span>
  </li>
  {% else %}
  <li class="page-item">
    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
  </li>
  {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
    </a>
  </li>
  {% endif %}
</ul>

firstProject/templates/blog/sidebar.html
<div class="row mb-4">
  <div class="col-sm-3 p-0">
    <h3 class="bg-secondary text-light px-3 py-2 fw-light">最新記事</h2>
      <ul class="nav flex-column">
        <li class="nav-item mx-1 px-3 py-2 border-bottom border-secondary"><a href="#">テストページ</a></li>
        <li class="nav-item mx-1 px-3 py-2 border-bottom border-secondary"><a href="#">アプリケーションの作成</a></li>
        <li class="nav-item mx-1 px-3 py-2 border-bottom border-secondary"><a href="#">サーバの起動</a></li>
        <li class="nav-item mx-1 px-3 py-2 border-bottom border-secondary"><a href="#">Djangoのインストール</a></li>
        <li class="nav-item mx-1 px-3 py-2 border-bottom border-secondary"><a href="#">Djangoとは</a></li>
      </ul>
  </div>