photoProject/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/',
         auth_views.LoginView.as_view(template_name='accounts/login.html'),
         name='login'
    ),
    path('logout/',
        auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
        name='logout'
    )
]

photoProject/photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/', views.PostPhotoView.as_view(), name='post_photo'),
    path('mypage/', views.MyPageView.as_view(), name='mypage'),
    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),
    path('user_list/<int:id>/', views.UserListView.as_view(), name='user_list'),
    path('detail/<int:id>/', views.DetailPhotoView.as_view(), name='detail_photo'),
]

photoProject/photoProject/urls.py
from django.contrib import admin
from django.urls import path,include
from photo.views import IndexView
from django.conf import settings									
from django.conf.urls.static import static							

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('accounts/',include('accounts.urls')),
    path('photo/',include('photo.urls')),
    path('admin/', admin.site.urls),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photoProject/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    birthday = models.DateField(
        verbose_name='生年月日',
        null=True,
        blank=True
    )

photoProject/photo/models.py
from django.db import models
from accounts.models import CustomUser

class Category(models.Model):
    title = models.CharField(
        verbose_name='タイトル',
        max_length=20
    )

    def __str__(self):
        return self.title

class PhotoPost(models.Model):
    user = models.ForeignKey(
        to=CustomUser,
        verbose_name='ユーザ',
        on_delete=models.CASCADE,
        null=True
    )

    category = models.ForeignKey(
        to=Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT,
        null=True
    )

    title = models.CharField(
        verbose_name='タイトル',
        max_length=20
    )

    comment = models.TextField(
        verbose_name='コメント'
    )

    image1 = models.ImageField(
        verbose_name='イメージ1',
        upload_to='photos',
        null=True,
        blank=True
    )

    image2 = models.ImageField(
        verbose_name='イメージ2',
        upload_to='photos',
        null=True,
        blank=True
    )

    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )

    def __str__(self):
        return self.title

photoProject/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CreateCustomUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["username","birthday","email","password1","password2"]
        labels = {
            "username":"ユーザー名",
            "birthday": "誕生日",
            "email":"メールアドレス",
            "password1":"パスワード",
            "password2":"パスワード（確認用）",
        }

photoProject/photo/forms.py
from django import forms
from .models import PhotoPost

class SearchForm(forms.Form):
    key = forms.CharField(label='検索文字列')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['key'].widget.attrs['class'] = 'form-control'

class PhotoPostForm(forms.ModelForm):
    class Meta:
        model = PhotoPost
        fields = ['category','title','comment','image1','image2']
        labels = {
            'category':'カテゴリ',
            'title':'タイトル',
            'comment':'コメント',
            'image1':'イメージ1',
            'image2':'イメージ2',
        }

photoProject/accounts/views.py
from django.views.generic import TemplateView,CreateView
from django.urls import reverse_lazy
from .models import CustomUser
from .forms import CreateCustomUserForm

class SignUpView(CreateView):
    model = CustomUser											
    template_name ='accounts/signup.html'
    form_class = CreateCustomUserForm
    success_url = reverse_lazy('accounts:signup_success')

class SignUpSuccessView(TemplateView):
    template_name = 'accounts/signup_success.html'

photoProject/photo/views.py
from django.views.generic import TemplateView, ListView, DetailView,CreateView
from photo.models import PhotoPost
from .forms import SearchForm,PhotoPostForm
from django.db.models import Q
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator		
from django.contrib.auth.decorators import login_required

class IndexView(ListView):
    template_name = 'photo/index.html'
    context_object_name = 'photo_list'
    paginate_by = 4
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context
    def get_queryset(self):
        searchForm = SearchForm(self.request.GET)
        keyword = ''
        if searchForm.is_valid():
            keyword = searchForm.cleaned_data.get('key')
        queryset = PhotoPost.objects.filter(Q(title__contains=keyword) | Q(comment__contains=keyword)).order_by('-posted_at')
        return queryset
    
@method_decorator(login_required, name='dispatch')
class PostPhotoView(CreateView):
    model = PhotoPost
    template_name = 'photo/post_photo.html'
    form_class = PhotoPostForm
    success_url = reverse_lazy("photo:index")

    def form_valid(self, form):
        postdata = form.save(commit=False)
        
        postdata.user = self.request.user
        
        postdata.save()
        
        return super().form_valid(form)

class MyPageView(ListView):
    template_name = 'photo/mypage.html'
    context_object_name = 'photo_list'
    paginate_by = 4
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count'] = len(PhotoPost.objects.filter(user=self.request.user))
        return context
    def get_queryset(self):
        queryset = PhotoPost.objects.filter(user=self.request.user).order_by('-posted_at')
        return queryset

class CategoryView(ListView):
    template_name = 'photo/index.html'
    context_object_name = 'photo_list'
    paginate_by = 4
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context
    def get_queryset(self):
        category = self.kwargs.get('category', '')
        queryset = PhotoPost.objects.filter(category__title=category).order_by('-posted_at')
        return queryset

class UserListView(ListView):
    template_name = 'photo/index.html'
    context_object_name = 'photo_list'
    paginate_by = 4
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context
    def get_queryset(self):
        user_id = self.kwargs.get('id', 1)
        print(f"user_id{user_id}")
        queryset = PhotoPost.objects.filter(user=user_id).order_by('-posted_at')
        return queryset

class DetailPhotoView(DetailView):
    template_name = 'photo/detail.html'
    model = PhotoPost
    pk_url_kwarg = 'id'

photoProject/templates/accounts/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Sign in</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin">
  {% if form.errors %}
    <p style="color: red">ユーザー名とパスワードが一致しません。</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}  
    <img class="mb-4" src="{% static 'img/bootstrap-logo.svg' %}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">サインイン</h1>

    <div class="form-floating">
      <input type="text" class="form-control" name="username">
      <label for="floatingInput">ユーザ名</label>
    </div>
    <div class="form-floating">
      <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">パスワード</label>
    </div>
    <input class="w-100 btn btn-lg btn-primary"
               type="submit" value="ログイン">
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
    <input type="hidden" name="next" value="{% url 'photo:index' %}">
  </form>
</main>
  </body>
</html>

photoProject/templates/accounts/logout.html
{% extends 'photo/base.html'%}
{% load static %}

{% block title%}
Logout
{% endblock %}

{% block contents%}
<div class="container">
  <!-- 行を配置 -->
  <div class="row">
    <!-- 列の左右に余白offset-4を入れる
           列の上下パディングはpy-4 -->
    <div class="col offset-4 py-4">

      <h3>ログアウトしました</h3>
      <!-- トップページのリンクテキスト -->
      <p><a href="{% url 'photo:index' %}">トップページへ</a></p>
    </div>
  </div>
</div>
{% endblock %}

photoProject/templates/accounts/signup.html
{% extends 'photo/base.html'%}

{% block title%}
Sign up
{% endblock %}

{% block contents%}
<hr>
<div class="container">
  <!-- 行を配置 -->
  <div class="row">
    <!-- 列の左右に余白offset-2を入れる -->
    <div class="col offset-2">
      <h3>サインアップ</h3>
      <!-- サインアップのフォームを配置 -->
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
          <!-- ラベルを出力 -->
          {{ field.label_tag }}<br>
          <!-- <input>タグを出力 -->
          {{ field }}
        </p>
        {% endfor %}
        <!-- Sign upボタンを出力 -->
        <input type="submit" value="サインアップ">
      </form>
      <!-- トップページのリンクテキスト -->
      <br>
      <p><a href="{% url 'photo:index'%}">
          登録をやめてトップページに戻る</a>
      </p>
    </div>
  </div>
</div>

{% endblock %}

photoProject/templates/accounts/signup_success.html
{% extends 'photo/base.html'%}

{% block title%}
Sign up Success
{% endblock %}

{% block contents%}
<div class="container">
  <!-- 行を配置 -->
  <div class="row">
    <!-- 列の左右に余白offset-4を入れる
           列の上下パディングはpy-4 -->
    <div class="col offset-4 py-4">
      <h3>登録が完了しました</h3>
      <!-- ログインページのリンクテキスト -->
      <p><a href="login.html">ログインはこちら</a>
      <p>
    </div>
  </div>
</div>
{% endblock %}

photoProject/templates/photo/base.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <title>{% block title%}{% endblock %}</title>
  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


</head>

<body>

  <header>
    <div class="collapse bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">お気に入りを見つけよう</h4>
            <p class="text-muted">
              誰でも参加できる写真投稿サイトです。
              自分で撮影した写真なら何でもオッケー！
              でも、カテゴリに属する写真に限ります。
              コメントも付けてください！
            </p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Contact</h4>
            <ul class="list-unstyled">
              {% if user.is_authenticated %}
              <li><a href="javascript:logoutMenu.submit()" class="text-white">ログアウト</a></li>
              <form action='{% url "accounts:logout" %}' method='post' name='logoutMenu' style="display: none;">
                {% csrf_token %}
              </form>
              <li><a href="{% url 'photo:mypage' %}" class="text-white">{{ user.username }}</a></li>
              {% else %}
              <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
              <li><a href="{% url 'accounts:signup'%}" class="text-white">サインアップ</a></li>
              {% endif %}
              <li><a href="#" class="text-white">Email me</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container">
        <a href="{% url 'photo:index'%}" class="navbar-brand d-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
            stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
            viewBox="0 0 24 24">
            <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
            <circle cx="12" cy="13" r="4" />
          </svg>
          <strong>Photo Gallery</strong>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
          aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>

    </div>

  </header>

  <main>

    {% block contents%}{% endblock %}
  </main>

  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="{% url 'photo:index'%}">Back to top</a>
      </p>
      <!-- フッターのテキストを任意のものに書き換え-->
      <p class="mb-1">Photo Gallery is &copy; Bootstrap, but please post a lot!</p>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>

</html>

photoProject/templates/photo/detail.html
{% extends 'photo/base.html'%}
{% load static %}

{% block title%}
Photo Detail
{% endblock %}

{% block contents%}
<!-- Bootstrapのグリッドシステム -->
<br>
<div class="container">
  <!-- 行を配置 -->
  <div class="row">
    <!-- 列の左右に余白offset-3を入れる -->
    <div class="col offset-3">
      <!-- タイトル -->
      <h2>{{ object.title }}</h2>
      <!-- コメント -->
      <p>{{ object.comment }}</p>
      <br>
      <!-- 投稿日時 -->
      <p>{{ object.posted_at | date:"Y/m/d"}} {{ object.posted_at | time:"H:i" }}に投稿</p>
      <!-- 1枚目の写真 -->
      {% if object.image1 %}
      <p><img src="{{ object.image1.url }}"></img></p>
      {% else %}
      <p><img src="{% static 'img/snowman.png'%}"></img></p>
      {% endif %}
      <!-- 2枚目の写真が投稿されていたら表示する -->
      {% if object.image2 %}
      <p><img src="{{ object.image2.url }}"></img></p>
      {% else %}
      <p><img src="{% static 'img/snowman.png'%}"></img></p>
      {% endif %}

      <!-- 投稿写真がログイン中のユーザーのものであれば削除ボタンを表示 -->
      <form method="POST">
        <!-- リンク先のURL
           photo/<Photo postsテーブルのid値>/delete/ -->
        <a href="#" class="btn btn-primary my-2">削除する</a>

    </div>
  </div>
</div>
{% endblock %}

photoProject/templates/photo/index.html
{% extends 'photo/base.html'%}
{% load static %}

{% block title%}
Photo Gallery
{% endblock %}

{% block contents%}
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Photo Gallery</h1>
      <p class="lead text-muted">
        コメントを見て写真に描かれた世界に思いを馳せましょう。
        素敵な写真とコメントをお待ちしています!</p>
      <p>
        <a href="{% url 'photo:post_photo'%}" class="btn btn-primary my-2">投稿する</a>
        {% if user.is_authenticated %}
        <a href="javascript:logoutButton.submit()" class="btn btn-secondary my-2">ログアウト</a>
      <form action='{% url "accounts:logout" %}' method='post' name='logoutButton' style="display: none;">
        {% csrf_token %}
      </form>
      {% endif %}

      </p>
    </div>
  </div>
  <form method="GET" action="/">
    <div class="input-group mb-3" style="margin-top: 10px;">
      {{ search_form.key }}
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">検索</button>
      </div>
    </div>
  </form>
</section>

{% include 'photo/photo_list.html' %}
{% if is_paginated %}
{% include 'photo/pagenation.html'%}
{% endif %}
{% endblock%}

photoProject/templates/photo/mypage.html
{% extends 'photo/base.html' %}
{% load static %}

{% block title%}
My Page
{% endblock %}

{% block contents%}
<br>
<div style="text-align:center">
  <h4>テストさんのマイページ</h4>
  <p>投稿<strong>{{ count }}</strong>件</p>
  <a href="{% url 'photo:post_photo'%}">投稿する</a>
</div>
<hr>
{% include 'photo/photo_list.html' %}
{% include 'photo/pagenation.html'%}
{% endblock %}

photoProject/templates/photo/pagenation.html
<ul class="pagination" style="justify-content:center">
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
      <span aria-hidden="true">&laquo;</span>
    </a>
  </li>
  {% endif %}
  {% for num in paginator.page_range %}
  {% if page_obj.number == num %}
  <li class="page-item active">
    <span class="page-link">{{ num }}</span>
  </li>
  {% else %}
  <li class="page-item">
    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
  </li>
  {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
    </a>
  </li>
  {% endif %}
</ul>

photoProject/templates/photo/photo_delete.html
{% extends 'photo/base.html' %}
{% load static %}

{% block title%}
Photo Delete
{% endblock %}

{% block contents%}
<br>
<div class="container">
  <!-- 行を配置 -->
  <div class="row">
    <!-- 列の左右に余白offset-3を入れる -->
    <div class="col offset-3">
      <form method="POST">
        <br>
        <p>削除してもいいですか?</p>
        <button class="btn btn-primary my-2" type="submit">削除</button>
        <a href="#" class="btn btn-secondary my-2">キャンセル</a>
    </div>
  </div>
</div>
{% endblock %}

photoProject/templates/photo/photo_list.html
{% load static %}

<div class="album py-5 bg-light">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for photo in photo_list %}
      <div class="col">
        <div class="card shadow-sm">
          {% if photo.image1 %}
          <p><img src="{{ photo.image1.url }}"></img></p>
          {% elif photo.image2 %}
          <p><img src="{{ photo.image2.url }}"></img></p>
          {% else %}
          <p><img src="{% static 'img/snowman.png'%}"></img></p>
          {% endif %}

          <div class="card-body">
            <p class="card-text">{{photo.title}}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'photo:detail_photo' photo.pk%}" class="btn btn-sm btn-outline-secondary">詳細</a>
                <a href="{% url 'photo:category' photo.category.title%}" class="btn btn-sm btn-outline-secondary">
                  {{photo.category.title}}</a>
              </div>
              {% if photo.user %}
              <a href="{% url 'photo:user_list' photo.user.pk%}" class="text-decoration-none"><small
                  class="text-muted">{{photo.user.username}}</small></a>
              {% else %}
              <a href="#" class="text-decoration-none"><small class="text-muted">none</small></a>
              {% endif %}

            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

photoProject/templates/photo/post_photo.html
{% extends 'photo/base.html'%}
{% load static %}

{% block title%}
Post
{% endblock %}

{% block contents%}
<!-- Bootstrapのグリッドシステム -->
<br>
<div class="container">
  <!-- 行を配置 -->
  <div class="row">
    <!-- 列の左右に余白offset-2を入れる -->
    <div class="col offset-2">
      <!-- ファイルをアップロードする場合は
             enctype="multipart/form-data"が必要 -->
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
          {% for field in form %}
          <tr>
            <th>{{ field.label_tag }}</th>
            <td>{{ field }}</td>
          </tr>
          {% endfor %}
        </table>
        <hr>
        <button type="submit">投稿する</button>
      </form>
    </div>
  </div>
</div>
{% endblock%}